name: Build and publish wheels

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run unit tests
        run: uv run --no-dev --all-extras --with pytest pytest tests

      - name: Build wheels
        run: uv build

      - name: Publish wheels
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
